admin:
  id: admin
  username: admin
  password: "yH9ikfIht+apbbuTRCk+pqLdRpWzoYA4fBaBfEPc9ASj+nnPYR1Ki0gr27lnpxVJ"
  email: admin@dev.null
  read: ['/'] # read and edit everything
  write: ['/']
  publish: true
view:
  id: view
  username: view
  password: "y9B1KgX/WXd55xVa/oiRrPvkAT+iEQtksXmRL+DrrW5KXSVFIM0hEeIxjPV5veqx"
  email: view@dev.null
  read: ['/'] # can read everything
  write: []   # and write nothing
  publish: false
draft:
  id: draft
  username: draft
  password: "wrFzzrONlOV4NU81DerBD0Q+m4rUhV9NrrF4DsSG4VZ2G4V1RY8mMtmR3emDpm7l"
  email: draft@dev.null
  read: ['/'] # read everything
  write: ['/draft', '/blog/draft' ] # write under test
  publish: false
blog:
  id: blog
  username: blog
  password: "NV6+PJSkJ6jp4G0wjVMeGoNv5GGgVPe7ky5MyTOO3PQPKBXTh1fBjFGqxG85PkFQ"
  email: blog@dev.null
  read: ['/blog']  # read and edit only onder blog
  write: ['/blog']
  publish: true
